### ISSUE TITLE
missing GetLoadWindow functions in DIRECT_Framework

### ISSUE THREAD

**Issue by tomamourette** [RoelantVos/DIRECT#16]
I have found that the Solution is reporting that some functions are missing:

![image](https://user-images.githubusercontent.com/21061154/120306018-b5dc5000-c2d1-11eb-9672-1758ad8cb1aa.png)

**Comment by RoelantVos** [comment]
Thanks for reporting, I renamed the function but hadn't built the solution. Oddly enough the dacpac seemed OK, so not sure what happened. Anyway it's fixed in this commit: https://github.com/RoelantVos/DIRECT/commit/cfe4e574ffdf61cdc65774f7678e32e7ef6ab9ef.

- GetLoadWindowDateTimes has been repointed to the new name **GetModuleLoadWindowDateTime**
- GetLoadWindowModuleInstance has been repointed to the new name **GetModuleLoadWindowIdentifier**
